# Generated by Django 4.1.7 on 2023-03-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_uploader",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
