# Generated by Django 4.1.7 on 2023-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0002_alter_image_uploader_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_uploader",
            name="file",
            field=models.ImageField(upload_to="images"),
        ),
    ]
